### ISSUE TITLE
Is possible not to use edit button on setting view?

### ISSUE THREAD

**Issue by oddukgi** [oklemenz/OKit#2]
Thank you giving reply of past question.
I subclass `ModelDetailTableController` on my customVC.
I draw UISldier and UISwitch on section.
I want to edit UISlider and UISwitch directly. 

**Pic. Apply OKit on SettingVC**
<img width="225" alt="SettingVC" src="https://user-images.githubusercontent.com/3068049/89700304-12980400-d968-11ea-88cd-d35a444634bc.png">

**Comment by oklemenz** [comment]
Sub-classing the Model List Controller can be problematic, as base functionality may be overridden. So always super shall be called to keep binding workings. "editAlways" property is available to have VC always in edit mode. Set that to #true. And you can remove the edit button from bar.
